apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=804d4b8ca6bc4c2cf02c5c971aa923ec5b8623f0 # v2.8.0

# Ignoring deprecation for now
# https://github.com/kubernetes-sigs/kustomize/issues/5049
patchesStrategicMerge:
- patches/configure_argocd-cm.yaml
- patches/set_liveness_and_readiness_probes.yaml
- patches/set_resource_limits_and_requests.yaml

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-redis
  patch: |-
    # set max memory to 65% of requested memory
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --maxmemory 84mb
- target:
    group: networking.k8s.io
    version: v1
    kind: NetworkPolicy
  patch: |-
    # allow egress traffic
    - op: add
      path: /spec/egress
      value: [{}]
    - op: replace
      path: /spec/policyTypes
      value:
      - Ingress
      - Egress

configMapGenerator:
- name: argocd-cmd-params-cm
  behavior: replace
  literals:
  - reposerver.parallelism.limit=1
  - server.insecure=true
- name: argocd-rbac-cm
  behavior: replace
  literals:
  - policy.default=role:readonly
