apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/fluxcd/source-controller/config/default?ref=3f131a1834d11b11db77091650d8080d432e14f9 # v1.2.4
- serviceaccount.yaml
- networkpolicy.yaml

labels:
- pairs:
    app.kubernetes.io/component: source-controller
  includeSelectors: true

images:
- name: fluxcd/source-controller
  newName: ghcr.io/fluxcd/source-controller

patches:
- path: patches/delete_namespace.yaml
- path: patches/use_serviceaccount.yaml
- path: patches/set_resources_limits_requests.yaml
