apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/fluxcd/source-controller/config/default?ref=a80a99b359f964d92c70f119195be34ca8438f89 # v1.3.0
- serviceaccount.yaml
- networkpolicy.yaml

labels:
- pairs:
    app.kubernetes.io/component: source-controller
  includeSelectors: true

images:
- name: fluxcd/source-controller
  newName: ghcr.io/fluxcd/source-controller

patches:
- path: patches/delete_namespace.yaml
- path: patches/use_serviceaccount.yaml
- path: patches/set_resources_limits_requests.yaml
