apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/fluxcd/source-controller/config/default?ref=8b83c8bf8ed1f44c3f2e4a02ea980fcddabb67dc # v1.1.2
- serviceaccount.yaml
- networkpolicy.yaml

labels:
- pairs:
    app.kubernetes.io/component: source-controller
  includeSelectors: true

images:
- name: fluxcd/source-controller
  newName: ghcr.io/fluxcd/source-controller

patches:
- path: patches/delete_namespace.yaml
- path: patches/use_serviceaccount.yaml
- path: patches/set_resources_limits_requests.yaml
