apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/fluxcd/source-controller/config/default?ref=0e47f7fa1afb77fe7027e3d0d9986bb141792bec # v1.1.0
- serviceaccount.yaml
- networkpolicy.yaml

labels:
- pairs:
    app.kubernetes.io/component: source-controller
  includeSelectors: true

images:
- name: fluxcd/source-controller
  newName: ghcr.io/fluxcd/source-controller

# Ignoring deprecation for now
# https://github.com/kubernetes-sigs/kustomize/issues/5049
patchesStrategicMerge:
- patches/delete_namespace.yaml
- patches/use_serviceaccount.yaml
- patches/set_resources_limits_requests.yaml
