apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: source-controller
spec:
  egress:
  - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/component: source-controller
  policyTypes:
  - Egress
