apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-admission
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/managed-by: Helm
spec:
  egress:
  - {}
  podSelector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: admission-webhook
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Egress
