apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/name: grafana
  namespace: parca
data:
  GF_DEFAULT_APP_MODE: development
  GF_INSTALL_PLUGINS: https://storage.googleapis.com/grafana-plugins-review/parca-datasource-plugin-0.0.2.zip;parca-datasource,https://storage.googleapis.com/grafana-plugins-review/parca-panel-plugin-0.0.2.zip;parca-panel
