apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: parca
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: 2.39.0
  name: parca
  namespace: monitoring
spec:
  enableFeatures: []
  externalLabels: {}
  image: quay.io/prometheus/prometheus:v2.39.0
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: parca
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/version: 2.39.0
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  replicas: 1
  resources:
    requests:
      memory: 400Mi
  ruleNamespaceSelector: {}
  ruleSelector: {}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-parca
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: 2.39.0
  remoteWrite:
  - url: https://demo.pyrra.dev/prometheus/api/v1/write
    writeRelabelConfigs:
    - action: keep
      regex: parca/parca-agent
      sourceLabels:
      - job


