apiVersion: rbac.authorization.k8s.io/v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: parca
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/version: 2.39.0
    name: prometheus-parca
    namespace: parca
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: prometheus-parca
  subjects:
  - kind: ServiceAccount
    name: prometheus-parca
    namespace: monitoring
kind: RoleBindingList
