apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca-agent
    app.kubernetes.io/name: parca-agent
    prometheus: parca
  name: parca-agent
  namespace: parca
spec:
  podMetricsEndpoints:
  - port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: parca-agent
