apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: parca
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: 2.39.0
  name: prometheus-parca
  namespace: monitoring
