---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: parca-dev-demo-deployments
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://git@github.com/parca-dev/demo-deployments.git
  secretRef:
    name: flux-ssh-credentials
