apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: parca-dev-demo-deployments
spec:
  sourceRef:
    kind: GitRepository
    name: parca-dev-demo-deployments
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: 'chore(deploy): update from image update automation'
  interval: 1m0s
  update:
    strategy: Setters
