apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: parca-dev-demo-deployments
spec:
  sourceRef:
    kind: GitRepository
    name: parca-dev-demo-deployments
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |-
        chore(deploy): update {{ range $i, $image := .Updated.Images -}}
          {{- if $i }}, {{ end }}{{ $image -}}
        {{- end }}
  interval: 1m0s
  update:
    strategy: Setters
