apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
- ../../base
- gitrepository.yaml
- imagepolicies.yaml
- imagerepositories.yaml
- imageupdateautomation.yaml
- ssh-credentials-secret.yaml
