apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  ingressClassName: nginx
  rules:
  - host: demo.parca.dev
    http:
      paths:
      - backend:
          service:
            name: argocd-server
            port:
              name: http
        path: /argo-cd
        pathType: Prefix
