apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ../../base
- argocd-server-ingress.yaml

configMapGenerator:
- name: argocd-cm
  namespace: argocd
  behavior: merge
  literals:
  - url=https://argocd.parca.dev
  files:
  - dex.config=files/dex.config.yaml
- name: argocd-rbac-cm
  namespace: argocd
  behavior: merge
  files:
  - files/policy.csv
