apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ../../base
- argocd-server-ingress.yaml

patches:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: argocd-server
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --rootpath=/argo-cd


configMapGenerator:
- name: argocd-cm
  namespace: argocd
  behavior: merge
  literals:
  - url=https://demo.parca.dev/argo-cd
  files:
  - dex.config=files/dex.config.yaml
- name: argocd-rbac-cm
  namespace: argocd
  behavior: merge
  files:
  - files/policy.csv
