apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/component: authentication-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: oauth2-proxy
    app.kubernetes.io/managed-by: Helm
spec:
  egress:
  - {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
          app.kubernetes.io/component: controller
          app.kubernetes.io/instance: ingress-nginx
    ports:
    - port: http
  podSelector:
    matchLabels:
      app.kubernetes.io/name: oauth2-proxy
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Egress
  - Ingress
