apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  labels:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/component: authentication-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: oauth2-proxy
    app.kubernetes.io/managed-by: Helm
