apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- image-automation-controller
- image-reflector-controller
- source-controller

labels:
- pairs:
    app.kubernetes.io/name: flux
  includeSelectors: true
