apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  egress:
  - {}
  ingress:
  - ports:
    - port: web
    - port: websecure
  podSelector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: Helm
  policyTypes:
  - Egress
  - Ingress
