apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-reflector-controller
spec:
  template:
    spec:
      containers:
      - name: manager
        resources:
          limits:
            cpu: null
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
