---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-reflector-controller
spec:
  template:
    spec:
      serviceAccountName: image-reflector-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: image-reflector-leader-election-rolebinding
subjects:
- kind: ServiceAccount
  name: image-reflector-controller
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: image-reflector-manager-rolebinding
subjects:
- kind: ServiceAccount
  name: image-reflector-controller
  namespace: flux-system
