---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-controller
spec:
  template:
    spec:
      serviceAccountName: source-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: source-leader-election-rolebinding
subjects:
- kind: ServiceAccount
  name: source-controller
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: source-manager-rolebinding
subjects:
- kind: ServiceAccount
  name: source-controller
  namespace: flux-system
