cert-manager:
  installCRDs: true

  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 128Mi

  webhook:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 128Mi

  cainjector:
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        memory: 128Mi
