---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  admin.enabled: 'false'
  application.resourceTrackingMethod: annotation
  resource.exclusions: |
    - apiGroups:
      - tanka.dev
      kinds:
      - Environment
      clusters:
      - '*'
  users.anonymous.enabled: 'true'
  statusbadge.enabled: 'true'
